apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: christianloewel-poi-backend-app-dev
  annotations:
    argocd/app-name: christianloewel-poi-backend-app-dev
    backstage.io/kubernetes-id: christianloewel-poi-backend-app
    backstage.io/kubernetes-namespace: christianloewel
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh23-lab/christianloewel-backend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-m9x67.dusy.p1.openshiftapps.com/dev-pipelines/ns/christianloewel/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-m9x67.dusy.p1.openshiftapps.com/k8s/ns/christianloewel/deployments/christianloewel-poi-backend-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-m9x67.dusy.p1.openshiftapps.com/#https://github.com/rhdh23-lab/christianloewel-backend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/christianloewel"
  system: workshop-system-christianloewel
  providesApis:
    - backend-api-christianloewel
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-christianloewel
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/christianloewel"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backend-api-christianloewel
  description: API surface used by workshop attendees to initialize and load parks data
  links:
    - url: http://christianloewel-poi-backend-app-christianloewel.apps.rosa-m9x67.dusy.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rhdh23-lab/christianloewel-backend/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/christianloewel"
  system: workshop-system-christianloewel
  definition:
    $text: https://github.com/rhdh23-lab/christianloewel-backend/tree/main/src/main/resources/META-INF/openapi.yaml
